"""Create STAR schema CampusRecruitment

Revision ID: 2b2fd1b0d923
Revises: 
Create Date: 2023-12-13 11:30:23.197888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2fd1b0d923'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_datum',
    sa.Column('datumId', sa.Integer(), nullable=False),
    sa.Column('jaar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datumId')
    )
    op.create_table('dim_diploma',
    sa.Column('diplomaId', sa.Integer(), nullable=False),
    sa.Column('diplomaSoort', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('diplomaId')
    )
    op.create_table('dim_onderwijsinstelling',
    sa.Column('onderwijsInstellingId', sa.Integer(), nullable=False),
    sa.Column('instellingsnaamActueel', sa.String(), nullable=True),
    sa.Column('provincie', sa.String(), nullable=True),
    sa.Column('gemeenteNaam', sa.String(), nullable=True),
    sa.Column('gemeenteNummer', sa.Integer(), nullable=True),
    sa.Column('soortInstelling', sa.String(), nullable=True),
    sa.Column('brinNummerActueel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('onderwijsInstellingId')
    )
    op.create_table('dim_opleiding',
    sa.Column('opleidingId', sa.Integer(), nullable=False),
    sa.Column('opleidingsCode', sa.Integer(), nullable=True),
    sa.Column('opleidingsNaam', sa.String(), nullable=True),
    sa.Column('opleidingsVorm', sa.String(), nullable=True),
    sa.Column('crohoOnderdeel', sa.String(), nullable=True),
    sa.Column('crohoSubOnderdeel', sa.String(), nullable=True),
    sa.Column('isVoltijd', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('opleidingId')
    )
    op.create_table('dim_student',
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('geslacht', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('studentId')
    )
    op.create_table('feit_student_studeert_af_aan_onderwijsinstelling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datumId', sa.Integer(), nullable=False),
    sa.Column('onderwijsinstellingId', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('opleidingId', sa.Integer(), nullable=False),
    sa.Column('dimplomaId', sa.Integer(), nullable=False),
    sa.Column('aantalAfgestudeerden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datumId'], ['dim_datum.datumId'], ),
    sa.ForeignKeyConstraint(['dimplomaId'], ['dim_diploma.diplomaId'], ),
    sa.ForeignKeyConstraint(['onderwijsinstellingId'], ['dim_onderwijsinstelling.onderwijsInstellingId'], ),
    sa.ForeignKeyConstraint(['opleidingId'], ['dim_opleiding.opleidingId'], ),
    sa.ForeignKeyConstraint(['studentId'], ['dim_student.studentId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feit_student_studeert_af_aan_onderwijsinstelling')
    op.drop_table('dim_student')
    op.drop_table('dim_opleiding')
    op.drop_table('dim_onderwijsinstelling')
    op.drop_table('dim_diploma')
    op.drop_table('dim_datum')
    # ### end Alembic commands ###
